### PR TITLE
Chapter 25 Exercise 3

### PR DESCRIPTION
**Pull request by ARazaMaths**
Parts a) and b) are formalised with solutions.

### CODE REVIEW

**Comment by kbuzzard** [comment]
Thanks! I've now added a bunch more exercises; can you move the file to `M1FExplained/Chapter25/Exercises/Exercise03.lean`?

Chapter 25 is an introduction to group theory and the axioms have just been introduced.  In your proof of part a you only use the axioms, but in your proof of part b you also use `inv_eq_of_mul_eq_one_right`, which is not an axiom of group theory and is also not proved in Chapter 25, so probably you should prove it just using the axioms of group theory if you want to give a proof in the spirit of the book. Proposition 25.1(ii) is close but it assumes a bit too much; however I think the proof technique of 25.1(ii) should be usable to prove `inv_eq_of_mul_eq_one_right`. What do you think?

**Comment by kbuzzard** [comment]
Oh two more things: (1) Can you edit README.md and add your name a contributor and (2) I think these proofs would look nicer as `calc` proofs -- they would be much more readable. Do you know how to set up a calc proof in Lean 4?

**Comment by kbuzzard** [comment]
The way to fix conflicts is to update master on your local machine and then merge it into your branch. Sorry git is quite complicated to use. If you can't sort it out don't worry, I can do it.

**Comment by ARazaMaths** [comment]
I have changed part i) to be a `calc` proof and part ii) to not use `inv_eq_of_mul_eq_one_right`. I have also added the question in the .lean file. Additionally, I have merged with the main branch and have updated the README.

**Comment by kbuzzard** [comment]
Thanks!

**Pull request merged**
